name: 💡 General Feature Request
description: Have a new idea/feature for Uemcrp? Please suggest!
title: "[FEATURE] <description>"
labels: ["⭐ goal: addition", "good first issue", "🤩 Up for the grab", "hacktoberfest"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the enhancement you propose, also include what you tried and what worked.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: |
        Is there anything else we should know about this idea?
        ## **Make sure to read the [CONTRIBUTING](https://github.com/warmachine028/uemcrp/blob/main/CONTRIBUTING.md) and [SETUP](https://github.com/warmachine028/uemcrp/tree/main/rules) docs before proceeding**
        ## Happy contributing. 💐
        Star my other Repositories [here](https://github.com/warmachine028)
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## **Make sure to read the [CONTRIBUTING](https://github.com/warmachine028/uemcrp/blob/main/CONTRIBUTING.md) and [SETUP](https://github.com/warmachine028/uemcrp/tree/main/rules) docs before proceeding**
        ## Happy contributing. 💐
        Star my other Repositories [here](https://github.com/warmachine028)

